name: "mnist_conv"
seed: 42
max_iter: 100000
print_after: 1000
save_after: 10000
validate_after: 1000
reduce_lr_factor: 0.5
reduce_lr_num_steps: 6
reduce_lr_max: 10
reduce_lr_threshold: 0.0
checkpoint_dir: "./checkpoint_dir"
display: false
display_after: 100

layer {
  name: "input"
  num_channels: 1
  display: true
  image_size_y: 28
  image_size_x: 28
}

layer {
  name: "hidden1_conv"
  num_channels: 48
  activation: RECTIFIED_LINEAR
}

layer {
  name: "hidden1_maxpool"
  num_channels: 48
}

layer {
  name: "hidden2_conv"
  num_channels: 128
  activation: RECTIFIED_LINEAR
}

layer {
  name: "hidden2_maxpool"
  num_channels: 128
}

layer {
  name: "output"
  num_channels: 10
  activation: SOFTMAX
}

edge {
  source: "input"
  dest: "hidden1_conv"
  edge_type: CONVOLUTIONAL
  kernel_size: 4
  shared_bias: true
  initialization: DENSE_UNIFORM_SQRT_FAN_IN
  init_wt: 1.0
  init_bias: 0.0
  weight_optimizer {
    epsilon: 0.01
    initial_momentum : 0.5
    final_momentum : 0.95
    l2_decay: 0.0005
  }
  bias_optimizer {
    epsilon: 0.01
    final_momentum : 0.95
  }
  partial_sum: 4
}

edge {
  source: "hidden1_conv"
  dest: "hidden1_maxpool"
  edge_type: MAXPOOL
  kernel_size: 4
  stride : 2
}

edge {
  source: "hidden1_maxpool"
  dest: "hidden2_conv"
  edge_type: CONVOLUTIONAL
  kernel_size: 4
  shared_bias: true
  initialization: DENSE_UNIFORM_SQRT_FAN_IN
  init_wt: 1.0
  init_bias: 1.0
  weight_optimizer {
    epsilon: 0.01
    initial_momentum : 0.5
    final_momentum : 0.95
    l2_decay: 0.0005
  }
  bias_optimizer {
    epsilon: 0.01
    final_momentum : 0.95
  }
  partial_sum: 13
}

edge {
  source: "hidden2_conv"
  dest: "hidden2_maxpool"
  edge_type: MAXPOOL
  kernel_size: 4
  stride : 2
}

edge {
  source: "hidden2_maxpool"
  dest: "output"
  edge_type: FC
  initialization: DENSE_UNIFORM_SQRT_FAN_IN
  init_wt: 1.0
  weight_optimizer {
    epsilon: 0.01
    initial_momentum : 0.5
    final_momentum : 0.95
    weight_norm_limit: 4
    l2_decay: 0.0005
  }
  bias_optimizer {
    epsilon: 0.01
    final_momentum : 0.95
  }
}

