data_config {
  file_pattern: "/ais/gobi3/u/nitish/mnist/mnist.h5"
  layer_name: "input"
  dataset_name: "validation"
  data_type: HDF5
}
data_config {
  file_pattern: "/ais/gobi3/u/nitish/mnist/mnist.h5"
  layer_name: "output"
  dataset_name: "validation_labels"
  data_type: HDF5
}
batch_size : 100
